before_script:
  - apk update && apk add make git

test:5.0:
  image: bash:5.0
  script:
    - make test

test:4.4:
  image: bash:4.4
  script:
    - make test

test:4.3:
  image: bash:4.3
  allow_failure: true
  script:
    - make test

test:4.2:
  image: bash:4.2
  allow_failure: true
  script:
    - make test

test:4.1:
  image: bash:4.1
  allow_failure: true
  script:
    - make test

test:4.0:
  image: bash:4.0
  allow_failure: true
  script:
    - make test

test:3.2:
  image: bash:3.2
  allow_failure: true
  script:
    - make test
